name: Register
on:
  push:
    branches:
      - main
    paths:
      - 'Project.toml'
      - 'src/**'
  workflow_dispatch:
jobs:
  register:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: JuliaRegistries/RegisterAction@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
